import type { Language } from '../types';
import type { SupportActionId } from '../lib/api';

type ActionLabels = Record<SupportActionId, string>;

const en: ActionLabels = {
  parent_handling: 'I am handling this',
  parent_escalate: 'Escalate to backup',
  parent_mark_with_adult: 'Child is with an adult',
  caregiver_take_over: 'Caregiver taking over',
  caregiver_called_parent: 'Called the parent',
  caregiver_on_way: 'On the way',
  adult_self_monitor: 'Self-monitoring now',
  adult_treated_low: 'Treated the low',
  adult_need_help: 'Need backup help',
  adult_noting_high: 'Noting high glucose',
  parent_noting_high: 'Noting high reading',
};

const ru: ActionLabels = {
  parent_handling: 'Я беру ситуацию под контроль',
  parent_escalate: 'Эскалация к резерву',
  parent_mark_with_adult: 'Ребёнок с взрослым',
  caregiver_take_over: 'Caregiver берёт управление',
  caregiver_called_parent: 'Связался с родителем',
  caregiver_on_way: 'Уже в пути',
  adult_self_monitor: 'Слежу за собой',
  adult_treated_low: 'Обработал низкий сахар',
  adult_need_help: 'Нужна помощь',
  adult_noting_high: 'Зафиксировал высокий сахар',
  parent_noting_high: 'Зафиксировал высокое значение',
};

export const ACTION_LABELS: Record<Language, ActionLabels> = {
  en,
  ru,
  uk: {
    ...en,
    parent_handling: 'Я беру ситуацію під контроль',
    parent_escalate: 'Ескалація до резерву',
    parent_mark_with_adult: 'Дитина з дорослим',
    caregiver_take_over: 'Caregiver бере керування',
    caregiver_called_parent: 'Зв’язався з батьком',
    caregiver_on_way: 'Уже в дорозі',
    adult_self_monitor: 'Слідкую за собою',
    adult_treated_low: 'Обробив низький цукор',
    adult_need_help: 'Потрібна допомога',
  },
  es: {
    ...en,
    parent_handling: 'Estoy gestionando esto',
    parent_escalate: 'Escalar al respaldo',
    parent_mark_with_adult: 'El niño está con un adulto',
    caregiver_take_over: 'El cuidador toma el control',
    caregiver_called_parent: 'Llamé al padre',
    caregiver_on_way: 'En camino',
    adult_self_monitor: 'Automonitoreo activo',
    adult_treated_low: 'Traté la baja',
    adult_need_help: 'Necesito ayuda',
  },
  fr: {
    ...en,
    parent_handling: 'Je gère la situation',
    parent_escalate: 'Escalader vers le backup',
    parent_mark_with_adult: 'L’enfant est avec un adulte',
    caregiver_take_over: 'Le caregiver prend le relais',
    caregiver_called_parent: 'Parent contacté',
    caregiver_on_way: 'En route',
    adult_self_monitor: 'Auto-surveillance',
    adult_treated_low: 'Hypo traitée',
    adult_need_help: 'Besoin d’aide',
  },
  de: {
    ...en,
    parent_handling: 'Ich übernehme',
    parent_escalate: 'An Backup eskalieren',
    parent_mark_with_adult: 'Kind ist bei einem Erwachsenen',
    caregiver_take_over: 'Caregiver übernimmt',
    caregiver_called_parent: 'Elternteil kontaktiert',
    caregiver_on_way: 'Unterwegs',
    adult_self_monitor: 'Selbstüberwachung',
    adult_treated_low: 'Unterzucker behandelt',
    adult_need_help: 'Hilfe nötig',
  },
  zh: {
    ...en,
    parent_handling: '我来处理',
    parent_escalate: '升级到备用支持',
    parent_mark_with_adult: '孩子已与成人在一起',
    caregiver_take_over: 'Caregiver 接管',
    caregiver_called_parent: '已联系家长',
    caregiver_on_way: '正在前往',
    adult_self_monitor: '自我监测中',
    adult_treated_low: '已处理低血糖',
    adult_need_help: '需要备用帮助',
  },
  ja: {
    ...en,
    parent_handling: '対応中',
    parent_escalate: 'バックアップへエスカレート',
    parent_mark_with_adult: '子どもは大人と一緒',
    caregiver_take_over: 'Caregiver が引き継ぎ',
    caregiver_called_parent: '保護者に連絡済み',
    caregiver_on_way: '向かっています',
    adult_self_monitor: '自己モニター中',
    adult_treated_low: '低血糖を処理',
    adult_need_help: '支援が必要',
  },
  pt: {
    ...en,
    parent_handling: 'Estou cuidando disso',
    parent_escalate: 'Escalar para backup',
    parent_mark_with_adult: 'Criança está com adulto',
    caregiver_take_over: 'Caregiver assumindo',
    caregiver_called_parent: 'Pai/mãe contactado',
    caregiver_on_way: 'A caminho',
    adult_self_monitor: 'Autocontrolo ativo',
    adult_treated_low: 'Baixa tratada',
    adult_need_help: 'Preciso de ajuda',
  },
  he: {
    ...en,
    parent_handling: 'אני מטפל/ת בזה',
    parent_escalate: 'הסלמה לגיבוי',
    parent_mark_with_adult: 'הילד/ה עם מבוגר/ת',
    caregiver_take_over: 'Caregiver לוקח/ת שליטה',
    caregiver_called_parent: 'יצרתי קשר עם ההורה',
    caregiver_on_way: 'בדרך',
    adult_self_monitor: 'מנטר/ת את עצמי',
    adult_treated_low: 'טיפלתי בהיפו',
    adult_need_help: 'צריך/ה עזרה',
  },
  ar: {
    ...en,
    parent_handling: 'أتولى الموقف',
    parent_escalate: 'تصعيد إلى الدعم الاحتياطي',
    parent_mark_with_adult: 'الطفل مع شخص بالغ',
    caregiver_take_over: 'Caregiver يتولى',
    caregiver_called_parent: 'تم الاتصال بولي الأمر',
    caregiver_on_way: 'في الطريق',
    adult_self_monitor: 'مراقبة ذاتية',
    adult_treated_low: 'تمت معالجة الانخفاض',
    adult_need_help: 'أحتاج مساعدة',
  },
};
