import type { Language } from '../types';

export type DownloadPlatformCopy = {
  title: string;
  subtitle: string;
  installCta: string;
  downloadFileCta: string;
  downloadFileHint: string;
  installedTitle: string;
  installedBody: string;
  stepsTitle: string;
  steps: string[];
  otherPlatformLabel: string;
  note: string;
};

export type DownloadCopy = {
  footerSection: string;
  footerDesktop: string;
  footerMobile: string;
  footerPwa: string;
  desktop: DownloadPlatformCopy;
  mobile: DownloadPlatformCopy;
};

const en: DownloadCopy = {
  footerSection: 'Download',
  footerDesktop: 'Desktop',
  footerMobile: 'Mobile',
  footerPwa: 'PWA manifest',
  desktop: {
    title: 'Install Steady on desktop',
    subtitle: 'Add Steady to your computer for a calm, app-like window — no app store required.',
    installCta: 'Install on this device',
    downloadFileCta: 'Download desktop shortcut',
    downloadFileHint: 'Saves a shortcut file — open it to launch Steady on your computer.',
    installedTitle: 'Steady is ready on this device',
    installedBody: 'Open Steady from your dock, taskbar, or home screen like any other app.',
    stepsTitle: 'Manual install',
    steps: [
      'Open Steady in Chrome, Edge, or another supported browser.',
      'Look for Install or Add to Dock in the address bar or browser menu.',
      'Confirm install — Steady opens in its own window and keeps your sign-in.',
    ],
    otherPlatformLabel: 'Need the phone version?',
    note: 'Install works best over HTTPS. On shared computers, sign out when you are done.',
  },
  mobile: {
    title: 'Install Steady on mobile',
    subtitle: 'Save Steady to your home screen for quick access — like a native app, without an app store.',
    installCta: 'Install on this phone',
    downloadFileCta: 'Download mobile launcher',
    downloadFileHint: 'Saves a small HTML file — open it on your phone to add Steady to the home screen.',
    installedTitle: 'Steady is on your home screen',
    installedBody: 'Launch Steady from the icon anytime. Alerts and your workspace stay one tap away.',
    stepsTitle: 'Manual install',
    steps: [
      'Open Steady in Safari (iPhone/iPad) or Chrome (Android).',
      'iPhone/iPad: tap Share, then Add to Home Screen.',
      'Android: open the browser menu and choose Install app or Add to Home screen.',
    ],
    otherPlatformLabel: 'Need the desktop version?',
    note: 'Allow notifications after install if you want gentle safety alerts on this device.',
  },
};

const ru: DownloadCopy = {
  footerSection: 'Скачать',
  footerDesktop: 'Для компьютера',
  footerMobile: 'Для телефона',
  footerPwa: 'PWA-манифест',
  desktop: {
    title: 'Установить Steady на компьютер',
    subtitle: 'Добавьте Steady на рабочий стол — спокойное окно как у приложения, без магазина.',
    installCta: 'Установить на этом устройстве',
    downloadFileCta: 'Скачать ярлык для компьютера',
    downloadFileHint: 'Сохранится файл-ярлык — откройте его, чтобы запустить Steady.',
    installedTitle: 'Steady готов на этом устройстве',
    installedBody: 'Открывайте Steady с док-панели, панели задач или рабочего стола.',
    stepsTitle: 'Ручная установка',
    steps: [
      'Откройте Steady в Chrome, Edge или другом поддерживаемом браузере.',
      'Найдите «Установить» или «Add to Dock» в адресной строке или меню браузера.',
      'Подтвердите установку — Steady откроется в отдельном окне и сохранит вход.',
    ],
    otherPlatformLabel: 'Нужна версия для телефона?',
    note: 'Установка работает лучше по HTTPS. На общем компьютере выходите из аккаунта после работы.',
  },
  mobile: {
    title: 'Установить Steady на телефон',
    subtitle: 'Сохраните Steady на главный экран — как приложение, без магазина.',
    installCta: 'Установить на этом телефоне',
    downloadFileCta: 'Скачать файл для телефона',
    downloadFileHint: 'Сохранится HTML-файл — откройте его на телефоне, чтобы добавить Steady на главный экран.',
    installedTitle: 'Steady на главном экране',
    installedBody: 'Запускайте Steady по иконке. Рабочая зона и сигналы — в одно касание.',
    stepsTitle: 'Ручная установка',
    steps: [
      'Откройте Steady в Safari (iPhone/iPad) или Chrome (Android).',
      'iPhone/iPad: «Поделиться» → «На экран Домой».',
      'Android: меню браузера → «Установить приложение» или «На главный экран».',
    ],
    otherPlatformLabel: 'Нужна версия для компьютера?',
    note: 'После установки разрешите уведомления, если нужны мягкие сигналы безопасности.',
  },
};

export const DOWNLOAD_COPY: Record<Language, DownloadCopy> = {
  en,
  ru,
  uk: {
    ...en,
    footerSection: 'Завантажити',
    footerDesktop: 'Для компʼютера',
    footerMobile: 'Для телефону',
    desktop: {
      ...en.desktop,
      title: 'Встановити Steady на компʼютер',
      subtitle: 'Додайте Steady на робочий стіл — спокійне вікно як у застосунку.',
      installCta: 'Встановити на цьому пристрої',
      installedTitle: 'Steady готовий на цьому пристрої',
      installedBody: 'Відкривайте Steady з дока або панелі задач.',
      stepsTitle: 'Ручне встановлення',
      steps: [
        'Відкрийте Steady у Chrome, Edge або іншому браузері.',
        'Знайдіть «Install» або «Add to Dock» у рядку адреси чи меню.',
        'Підтвердіть — Steady відкриється в окремому вікні.',
      ],
      otherPlatformLabel: 'Потрібна версія для телефону?',
      note: 'Краще працює через HTTPS. На спільному ПК виходьте з акаунта.',
    },
    mobile: {
      ...en.mobile,
      title: 'Встановити Steady на телефон',
      subtitle: 'Збережіть Steady на головний екран — як застосунок.',
      installCta: 'Встановити на цьому телефоні',
      installedTitle: 'Steady на головному екрані',
      installedBody: 'Запускайте Steady з іконки в один дотик.',
      stepsTitle: 'Ручне встановлення',
      steps: [
        'Відкрийте Steady у Safari або Chrome.',
        'iPhone/iPad: «Поділитися» → «На Початковий екран».',
        'Android: меню → «Install app» або «На головний екран».',
      ],
      otherPlatformLabel: 'Потрібна версія для компʼютера?',
      note: 'Дозвольте сповіщення для мʼяких сигналів безпеки.',
    },
  },
  es: {
    ...en,
    footerSection: 'Descargar',
    footerDesktop: 'Escritorio',
    footerMobile: 'Móvil',
    desktop: {
      ...en.desktop,
      title: 'Instalar Steady en el escritorio',
      subtitle: 'Añade Steady a tu ordenador — una ventana tranquila, sin tienda de apps.',
      installCta: 'Instalar en este dispositivo',
      installedTitle: 'Steady está listo en este dispositivo',
      installedBody: 'Ábrelo desde el dock, la barra de tareas o el escritorio.',
      stepsTitle: 'Instalación manual',
      steps: [
        'Abre Steady en Chrome, Edge u otro navegador compatible.',
        'Busca Instalar o Añadir al dock en la barra de direcciones o el menú.',
        'Confirma — Steady se abrirá en su propia ventana.',
      ],
      otherPlatformLabel: '¿Necesitas la versión móvil?',
      note: 'Funciona mejor con HTTPS. En equipos compartidos, cierra sesión al terminar.',
    },
    mobile: {
      ...en.mobile,
      title: 'Instalar Steady en el móvil',
      subtitle: 'Guárdalo en la pantalla de inicio — como una app nativa.',
      installCta: 'Instalar en este teléfono',
      installedTitle: 'Steady está en tu pantalla de inicio',
      installedBody: 'Ábrelo desde el icono cuando lo necesites.',
      stepsTitle: 'Instalación manual',
      steps: [
        'Abre Steady en Safari (iPhone/iPad) o Chrome (Android).',
        'iPhone/iPad: Compartir → Añadir a pantalla de inicio.',
        'Android: menú → Instalar app o Añadir a pantalla de inicio.',
      ],
      otherPlatformLabel: '¿Necesitas la versión de escritorio?',
      note: 'Permite notificaciones si quieres alertas suaves en este dispositivo.',
    },
  },
  fr: {
    ...en,
    footerSection: 'Télécharger',
    footerDesktop: 'Ordinateur',
    footerMobile: 'Mobile',
    desktop: {
      ...en.desktop,
      title: 'Installer Steady sur ordinateur',
      subtitle: 'Ajoutez Steady à votre bureau — une fenêtre apaisante, sans store.',
      installCta: 'Installer sur cet appareil',
      installedTitle: 'Steady est prêt sur cet appareil',
      installedBody: 'Ouvrez Steady depuis le dock, la barre des tâches ou le bureau.',
      stepsTitle: 'Installation manuelle',
      steps: [
        'Ouvrez Steady dans Chrome, Edge ou un navigateur compatible.',
        'Cherchez Installer ou Ajouter au dock dans la barre d’adresse ou le menu.',
        'Confirmez — Steady s’ouvre dans sa propre fenêtre.',
      ],
      otherPlatformLabel: 'Besoin de la version mobile ?',
      note: 'Mieux en HTTPS. Sur un ordinateur partagé, déconnectez-vous après usage.',
    },
    mobile: {
      ...en.mobile,
      title: 'Installer Steady sur mobile',
      subtitle: 'Ajoutez Steady à l’écran d’accueil — comme une app native.',
      installCta: 'Installer sur ce téléphone',
      installedTitle: 'Steady est sur votre écran d’accueil',
      installedBody: 'Lancez Steady depuis l’icône en un geste.',
      stepsTitle: 'Installation manuelle',
      steps: [
        'Ouvrez Steady dans Safari (iPhone/iPad) ou Chrome (Android).',
        'iPhone/iPad : Partager → Sur l’écran d’accueil.',
        'Android : menu → Installer l’app ou Ajouter à l’écran d’accueil.',
      ],
      otherPlatformLabel: 'Besoin de la version ordinateur ?',
      note: 'Autorisez les notifications pour des alertes douces sur cet appareil.',
    },
  },
  de: {
    ...en,
    footerSection: 'Herunterladen',
    footerDesktop: 'Desktop',
    footerMobile: 'Mobil',
    desktop: {
      ...en.desktop,
      title: 'Steady auf dem Desktop installieren',
      subtitle: 'Steady zum Computer hinzufügen — ruhiges App-Fenster ohne Store.',
      installCta: 'Auf diesem Gerät installieren',
      installedTitle: 'Steady ist auf diesem Gerät bereit',
      installedBody: 'Öffnen Sie Steady über Dock, Taskleiste oder Desktop.',
      stepsTitle: 'Manuelle Installation',
      steps: [
        'Steady in Chrome, Edge oder einem unterstützten Browser öffnen.',
        'Installieren oder Zum Dock hinzufügen in Adressleiste oder Menü suchen.',
        'Bestätigen — Steady öffnet sich in einem eigenen Fenster.',
      ],
      otherPlatformLabel: 'Handy-Version nötig?',
      note: 'Am besten über HTTPS. Auf gemeinsamen Geräten abmelden.',
    },
    mobile: {
      ...en.mobile,
      title: 'Steady auf dem Handy installieren',
      subtitle: 'Steady zum Startbildschirm — wie eine native App.',
      installCta: 'Auf diesem Handy installieren',
      installedTitle: 'Steady ist auf dem Startbildschirm',
      installedBody: 'Steady jederzeit über das Icon starten.',
      stepsTitle: 'Manuelle Installation',
      steps: [
        'Steady in Safari (iPhone/iPad) oder Chrome (Android) öffnen.',
        'iPhone/iPad: Teilen → Zum Home-Bildschirm.',
        'Android: Menü → App installieren oder Zum Startbildschirm.',
      ],
      otherPlatformLabel: 'Desktop-Version nötig?',
      note: 'Benachrichtigungen erlauben für sanfte Sicherheitsalarme.',
    },
  },
  zh: {
    ...en,
    footerSection: '下载',
    footerDesktop: '桌面版',
    footerMobile: '移动版',
    desktop: {
      ...en.desktop,
      title: '在桌面安装 Steady',
      subtitle: '将 Steady 添加到电脑 — 像应用一样安静打开，无需应用商店。',
      installCta: '在此设备安装',
      installedTitle: 'Steady 已在此设备就绪',
      installedBody: '可从程序坞、任务栏或桌面打开。',
      stepsTitle: '手动安装',
      steps: [
        '在 Chrome、Edge 或其他支持的浏览器中打开 Steady。',
        '在地址栏或菜单中查找“安装”或“添加到程序坞”。',
        '确认后 Steady 会在独立窗口中打开。',
      ],
      otherPlatformLabel: '需要手机版？',
      note: 'HTTPS 下效果最佳。共用电脑用完后请退出登录。',
    },
    mobile: {
      ...en.mobile,
      title: '在手机上安装 Steady',
      subtitle: '保存到主屏幕 — 像原生应用一样，无需应用商店。',
      installCta: '在此手机安装',
      installedTitle: 'Steady 已在主屏幕',
      installedBody: '随时点击图标打开。',
      stepsTitle: '手动安装',
      steps: [
        '在 Safari（iPhone/iPad）或 Chrome（Android）中打开 Steady。',
        'iPhone/iPad：分享 → 添加到主屏幕。',
        'Android：菜单 → 安装应用或添加到主屏幕。',
      ],
      otherPlatformLabel: '需要桌面版？',
      note: '如需温和安全提醒，请在安装后允许通知。',
    },
  },
  ja: {
    ...en,
    footerSection: 'ダウンロード',
    footerDesktop: 'デスクトップ',
    footerMobile: 'モバイル',
    desktop: {
      ...en.desktop,
      title: 'デスクトップに Steady をインストール',
      subtitle: 'パソコンに Steady を追加 — ストア不要のアプリのような窓。',
      installCta: 'このデバイスにインストール',
      installedTitle: 'Steady はこのデバイスで使えます',
      installedBody: 'Dock、タスクバー、デスクトップから開けます。',
      stepsTitle: '手動インストール',
      steps: [
        'Chrome、Edge などで Steady を開く。',
        'アドレスバーまたはメニューで「インストール」を探す。',
        '確認すると Steady が独立ウィンドウで開きます。',
      ],
      otherPlatformLabel: 'スマホ版が必要ですか？',
      note: 'HTTPS で最も安定します。共用 PC では終了後にサインアウトしてください。',
    },
    mobile: {
      ...en.mobile,
      title: 'スマホに Steady をインストール',
      subtitle: 'ホーム画面に保存 — ネイティブアプリのように。',
      installCta: 'このスマホにインストール',
      installedTitle: 'Steady はホーム画面にあります',
      installedBody: 'アイコンからいつでも起動できます。',
      stepsTitle: '手動インストール',
      steps: [
        'Safari（iPhone/iPad）または Chrome（Android）で Steady を開く。',
        'iPhone/iPad：共有 → ホーム画面に追加。',
        'Android：メニュー → アプリをインストール。',
      ],
      otherPlatformLabel: 'デスクトップ版が必要ですか？',
      note: 'やさしい安全アラートには通知を許可してください。',
    },
  },
  pt: {
    ...en,
    footerSection: 'Baixar',
    footerDesktop: 'Desktop',
    footerMobile: 'Celular',
    desktop: {
      ...en.desktop,
      title: 'Instalar Steady no desktop',
      subtitle: 'Adicione Steady ao computador — janela calma, sem loja de apps.',
      installCta: 'Instalar neste dispositivo',
      installedTitle: 'Steady está pronto neste dispositivo',
      installedBody: 'Abra pelo dock, barra de tarefas ou área de trabalho.',
      stepsTitle: 'Instalação manual',
      steps: [
        'Abra Steady no Chrome, Edge ou outro navegador compatível.',
        'Procure Instalar ou Adicionar ao dock na barra de endereços ou menu.',
        'Confirme — Steady abrirá em janela própria.',
      ],
      otherPlatformLabel: 'Precisa da versão mobile?',
      note: 'Funciona melhor em HTTPS. Em PCs compartilhados, saia ao terminar.',
    },
    mobile: {
      ...en.mobile,
      title: 'Instalar Steady no celular',
      subtitle: 'Salve na tela inicial — como app nativo, sem loja.',
      installCta: 'Instalar neste celular',
      installedTitle: 'Steady está na tela inicial',
      installedBody: 'Abra pelo ícone quando precisar.',
      stepsTitle: 'Instalação manual',
      steps: [
        'Abra Steady no Safari (iPhone/iPad) ou Chrome (Android).',
        'iPhone/iPad: Compartilhar → Adicionar à Tela de Início.',
        'Android: menu → Instalar app ou Adicionar à tela inicial.',
      ],
      otherPlatformLabel: 'Precisa da versão desktop?',
      note: 'Permita notificações para alertas suaves neste dispositivo.',
    },
  },
  he: {
    ...en,
    footerSection: 'הורדה',
    footerDesktop: 'מחשב',
    footerMobile: 'נייד',
    desktop: {
      ...en.desktop,
      title: 'התקנת Steady במחשב',
      subtitle: 'הוסיפו את Steady למחשב — חלון רגוע כמו אפליקציה, בלי חנות.',
      installCta: 'התקנה במכשיר זה',
      installedTitle: 'Steady מוכן במכשיר זה',
      installedBody: 'פתחו מ-Dock, סרגל המשימות או שולחן העבודה.',
      stepsTitle: 'התקנה ידנית',
      steps: [
        'פתחו את Steady ב-Chrome, Edge או דפדפן נתמך.',
        'חפשו Install או Add to Dock בשורת הכתובת או בתפריט.',
        'אשרו — Steady ייפתח בחלון נפרד.',
      ],
      otherPlatformLabel: 'צריכים גרסה לנייד?',
      note: 'עובד הכי טוב ב-HTTPS. במחשב משותף — התנתקו בסיום.',
    },
    mobile: {
      ...en.mobile,
      title: 'התקנת Steady בנייד',
      subtitle: 'שמרו במסך הבית — כמו אפליקציה מקורית, בלי חנות.',
      installCta: 'התקנה בטלפון זה',
      installedTitle: 'Steady במסך הבית',
      installedBody: 'פתחו מהאייקון בכל עת.',
      stepsTitle: 'התקנה ידנית',
      steps: [
        'פתחו את Steady ב-Safari (iPhone/iPad) או Chrome (Android).',
        'iPhone/iPad: שיתוף → הוסף למסך הבית.',
        'Android: תפריט → התקן אפליקציה או הוסף למסך הבית.',
      ],
      otherPlatformLabel: 'צריכים גרסה למחשב?',
      note: 'אפשרו התראות להתראות בטיחות עדינות.',
    },
  },
  ar: {
    ...en,
    footerSection: 'تنزيل',
    footerDesktop: 'سطح المكتب',
    footerMobile: 'الجوال',
    desktop: {
      ...en.desktop,
      title: 'تثبيت Steady على سطح المكتب',
      subtitle: 'أضف Steady إلى جهازك — نافذة هادئة مثل التطبيق، بدون متجر.',
      installCta: 'تثبيت على هذا الجهاز',
      installedTitle: 'Steady جاهز على هذا الجهاز',
      installedBody: 'افتح Steady من Dock أو شريط المهام أو سطح المكتب.',
      stepsTitle: 'تثبيت يدوي',
      steps: [
        'افتح Steady في Chrome أو Edge أو متصفح مدعوم.',
        'ابحث عن Install أو Add to Dock في شريط العنوان أو القائمة.',
        'أكّد — Steady يفتح في نافذة مستقلة.',
      ],
      otherPlatformLabel: 'تحتاج نسخة الجوال؟',
      note: 'يعمل أفضل عبر HTTPS. على أجهزة مشتركة، سجّل الخروج بعد الانتهاء.',
    },
    mobile: {
      ...en.mobile,
      title: 'تثبيت Steady على الجوال',
      subtitle: 'احفظ Steady على الشاشة الرئيسية — مثل تطبيق أصلي.',
      installCta: 'تثبيت على هذا الهاتف',
      installedTitle: 'Steady على الشاشة الرئيسية',
      installedBody: 'افتح من الأيقونة في أي وقت.',
      stepsTitle: 'تثبيت يدوي',
      steps: [
        'افتح Steady في Safari (iPhone/iPad) أو Chrome (Android).',
        'iPhone/iPad: مشاركة → Add to Home Screen.',
        'Android: القائمة → Install app أو Add to Home screen.',
      ],
      otherPlatformLabel: 'تحتاج نسخة سطح المكتب؟',
      note: 'اسمح بالإشعارات لتنبيهات أمان لطيفة على هذا الجهاز.',
    },
  },
};
