import type { Language } from '../types';

export interface WorkspaceT2Labels {
  eyebrow: string;
  household: string;
  childCard: string;
  householdName: string;
  ageBand: string;
  primaryParent: string;
  caregiver: string;
  navFamily: { label: string; hint: string };
  sectionFamily: { title: string; subtitle: string };
  invite: { title: string; body: string };
  onboardingBullet3: string;
  setupEyebrow: string;
  setupTitle: string;
  setupSubtitle: string;
  setupSave: string;
}

export const WORKSPACE_T2_LABELS: Record<Language, WorkspaceT2Labels> = {
  en: {
    eyebrow: 'Type 2 Daily Support',
    household: 'Your Circle',
    childCard: 'Person With Diabetes',
    householdName: 'Support Circle Name',
    ageBand: 'Age Range',
    primaryParent: 'Partner Or Primary Contact',
    caregiver: 'Trusted Backup Contact',
    navFamily: { label: 'Circle', hint: 'People & invite' },
    sectionFamily: { title: 'Your support circle', subtitle: 'Who is in your circle and how to invite a partner or trusted contact.' },
    invite: { title: 'Invite someone to your circle', body: 'Share this code with a partner or trusted contact. They enter it during sign-up — no separate setup needed.' },
    onboardingBullet3: 'Timeline, connection, alerts, and your circle — in the menu.',
    setupEyebrow: 'Type 2 Setup',
    setupTitle: 'Set up your support circle',
    setupSubtitle: 'Add yourself, a partner, backup contact, and night window on one screen.',
    setupSave: 'Save Circle',
  },
  ru: {
    eyebrow: 'Ежедневная Поддержка T2',
    household: 'Ваш Круг',
    childCard: 'Человек С Диабетом',
    householdName: 'Название Круга Поддержки',
    ageBand: 'Возраст',
    primaryParent: 'Партнёр Или Основной Контакт',
    caregiver: 'Доверенный Резервный Контакт',
    navFamily: { label: 'Круг', hint: 'Люди и код' },
    sectionFamily: { title: 'Ваш круг поддержки', subtitle: 'Кто в круге и как пригласить партнёра или доверенный контакт.' },
    invite: { title: 'Пригласить в круг', body: 'Отправьте код партнёру или доверенному контакту. Его вводят при регистрации — отдельная настройка не нужна.' },
    onboardingBullet3: 'Хронология, связь, сигналы и круг — в меню.',
    setupEyebrow: 'Настройка T2',
    setupTitle: 'Настройте круг поддержки',
    setupSubtitle: 'Вы, партнёр, резервный контакт и ночное окно — на одном экране.',
    setupSave: 'Сохранить Круг',
  },
  uk: {
    eyebrow: 'Щоденна Підтримка T2',
    household: 'Ваше Коло',
    childCard: 'Людина З Діабетом',
    householdName: 'Назва Кола Підтримки',
    ageBand: 'Вік',
    primaryParent: 'Партнер Або Основний Контакт',
    caregiver: 'Довірений Резервний Контакт',
    navFamily: { label: 'Коло', hint: 'Люди та код' },
    sectionFamily: { title: 'Ваше коло підтримки', subtitle: 'Хто в колі і як запросити партнера або довірену людину.' },
    invite: { title: 'Запросити в коло', body: 'Надішліть код партнеру або довіреній людині. Його вводять під час реєстрації.' },
    onboardingBullet3: 'Хронологія, зв’язок, сигнали та коло — у меню.',
    setupEyebrow: 'Налаштування T2',
    setupTitle: 'Налаштуйте коло підтримки',
    setupSubtitle: 'Ви, партнер, резерв і нічне вікно — на одному екрані.',
    setupSave: 'Зберегти Коло',
  },
  es: {
    eyebrow: 'Apoyo Diario T2',
    household: 'Su Círculo',
    childCard: 'Persona Con Diabetes',
    householdName: 'Nombre Del Círculo',
    ageBand: 'Rango De Edad',
    primaryParent: 'Pareja O Contacto Principal',
    caregiver: 'Contacto De Reserva',
    navFamily: { label: 'Círculo', hint: 'Personas e invitación' },
    sectionFamily: { title: 'Su círculo de apoyo', subtitle: 'Quién está en el círculo y cómo invitar a pareja o contacto de confianza.' },
    invite: { title: 'Invitar al círculo', body: 'Comparta este código con su pareja o contacto de confianza. Lo ingresan al registrarse.' },
    onboardingBullet3: 'Línea, conexión, alertas y círculo — en el menú.',
    setupEyebrow: 'Configuración T2',
    setupTitle: 'Configure su círculo de apoyo',
    setupSubtitle: 'Usted, pareja, contacto de reserva y ventana nocturna — en una pantalla.',
    setupSave: 'Guardar Círculo',
  },
  fr: {
    eyebrow: 'Soutien Quotidien T2',
    household: 'Votre Cercle',
    childCard: 'Personne Avec Diabète',
    householdName: 'Nom Du Cercle',
    ageBand: 'Tranche D’âge',
    primaryParent: 'Partenaire Ou Contact Principal',
    caregiver: 'Contact De Secours',
    navFamily: { label: 'Cercle', hint: 'Personnes et code' },
    sectionFamily: { title: 'Votre cercle de soutien', subtitle: 'Qui est dans le cercle et comment inviter un partenaire ou contact de confiance.' },
    invite: { title: 'Inviter dans le cercle', body: 'Partagez ce code avec un partenaire ou contact de confiance. Il le saisit à l’inscription.' },
    onboardingBullet3: 'Chronologie, connexion, alertes et cercle — dans le menu.',
    setupEyebrow: 'Configuration T2',
    setupTitle: 'Configurez votre cercle de soutien',
    setupSubtitle: 'Vous, partenaire, relais et plage nocturne — sur un écran.',
    setupSave: 'Enregistrer Le Cercle',
  },
  de: {
    eyebrow: 'T2-Tägliche Unterstützung',
    household: 'Ihr Kreis',
    childCard: 'Person Mit Diabetes',
    householdName: 'Name Des Unterstützungskreises',
    ageBand: 'Altersbereich',
    primaryParent: 'Partner Oder Hauptkontakt',
    caregiver: 'Vertrauensvoller Reservekontakt',
    navFamily: { label: 'Kreis', hint: 'Personen & Code' },
    sectionFamily: { title: 'Ihr Unterstützungskreis', subtitle: 'Wer im Kreis ist und wie Partner oder Vertrauensperson eingeladen werden.' },
    invite: { title: 'In den Kreis einladen', body: 'Teilen Sie diesen Code mit Partner oder Vertrauensperson. Eingabe bei der Anmeldung.' },
    onboardingBullet3: 'Verlauf, Verbindung, Signale und Kreis — im Menü.',
    setupEyebrow: 'T2-Einrichtung',
    setupTitle: 'Unterstützungskreis einrichten',
    setupSubtitle: 'Sie, Partner, Reserve und Nachtfenster — auf einem Bildschirm.',
    setupSave: 'Kreis Speichern',
  },
  zh: {
    eyebrow: '2 型日常支持',
    household: '您的圈',
    childCard: '糖尿病患者',
    householdName: '支持圈名称',
    ageBand: '年龄段',
    primaryParent: '伴侣或主要联系人',
    caregiver: '可信后备联系人',
    navFamily: { label: '支持圈', hint: '成员与邀请' },
    sectionFamily: { title: '您的支持圈', subtitle: '圈内成员及如何邀请伴侣或可信联系人。' },
    invite: { title: '邀请加入支持圈', body: '将邀请码分享给伴侣或可信联系人，注册时输入即可。' },
    onboardingBullet3: '时间线、连接、提醒和支持圈 — 在菜单中。',
    setupEyebrow: '2 型设置',
    setupTitle: '设置支持圈',
    setupSubtitle: '您、伴侣、后备联系人和夜间窗口 — 同一页完成。',
    setupSave: '保存支持圈',
  },
  ja: {
    eyebrow: '2 型デイリーサポート',
    household: 'サークル',
    childCard: '糖尿病の方',
    householdName: 'サポートサークル名',
    ageBand: '年齢層',
    primaryParent: 'パートナーまたは主な連絡先',
    caregiver: '信頼できる予備連絡先',
    navFamily: { label: 'サークル', hint: 'メンバーと招待' },
    sectionFamily: { title: 'サポートサークル', subtitle: 'メンバーと、パートナーや信頼できる連絡先の招待方法。' },
    invite: { title: 'サークルに招待', body: 'パートナーや信頼できる連絡先にコードを共有。登録時に入力します。' },
    onboardingBullet3: 'タイムライン、接続、アラート、サークル — メニューにあります。',
    setupEyebrow: '2 型セットアップ',
    setupTitle: 'サポートサークルを設定',
    setupSubtitle: '本人、パートナー、予備連絡先、夜間ウィンドウ — 1画面で。',
    setupSave: 'サークルを保存',
  },
  pt: {
    eyebrow: 'Apoio Diário T2',
    household: 'Seu Círculo',
    childCard: 'Pessoa Com Diabetes',
    householdName: 'Nome Do Círculo',
    ageBand: 'Faixa Etária',
    primaryParent: 'Parceiro Ou Contato Principal',
    caregiver: 'Contato De Reserva',
    navFamily: { label: 'Círculo', hint: 'Pessoas e convite' },
    sectionFamily: { title: 'Seu círculo de apoio', subtitle: 'Quem está no círculo e como convidar parceiro ou contato de confiança.' },
    invite: { title: 'Convidar para o círculo', body: 'Compartilhe este código com parceiro ou contato de confiança. Eles digitam no cadastro.' },
    onboardingBullet3: 'Linha do tempo, conexão, alertas e círculo — no menu.',
    setupEyebrow: 'Configuração T2',
    setupTitle: 'Configure seu círculo de apoio',
    setupSubtitle: 'Você, parceiro, reserva e janela noturna — em uma tela.',
    setupSave: 'Salvar Círculo',
  },
  he: {
    eyebrow: 'תמיכה יומית T2',
    household: 'המעגל שלך',
    childCard: 'אדם עם סוכרת',
    householdName: 'שם מעגל התמיכה',
    ageBand: 'טווח גיל',
    primaryParent: 'בן/בת זוג או איש קשר ראשי',
    caregiver: 'איש קשר גיבוי',
    navFamily: { label: 'מעגל', hint: 'אנשים והזמנה' },
    sectionFamily: { title: 'מעגל התמיכה שלך', subtitle: 'מי במעגל ואיך להזמין בן/בת זוג או איש קשר מהימן.' },
    invite: { title: 'הזמנה למעגל', body: 'שתפו את הקוד עם בן/בת זוג או איש קשר. הם מזינים אותו בהרשמה.' },
    onboardingBullet3: 'ציר זמן, חיבור, התראות ומעגל — בתפריט.',
    setupEyebrow: 'הגדרת T2',
    setupTitle: 'הגדירו מעגל תמיכה',
    setupSubtitle: 'אתם, בן/בת זוג, גיבוי וחלון לילה — במסך אחד.',
    setupSave: 'שמור מעגל',
  },
  ar: {
    eyebrow: 'دعم يومي T2',
    household: 'دائرتك',
    childCard: 'الشخص المصاب بالسكري',
    householdName: 'اسم دائرة الدعم',
    ageBand: 'الفئة العمرية',
    primaryParent: 'الشريك أو جهة الاتصال الأساسية',
    caregiver: 'جهة اتصال احتياطية',
    navFamily: { label: 'الدائرة', hint: 'الأشخاص والدعوة' },
    sectionFamily: { title: 'دائرة دعمك', subtitle: 'من في الدائرة وكيف تدعو شريكًا أو جهة اتصال موثوقة.' },
    invite: { title: 'دعوة إلى الدائرة', body: 'شارك هذا الرمز مع شريك أو جهة اتصال موثوقة. يدخلونه عند التسجيل.' },
    onboardingBullet3: 'الجدول الزمني والاتصال والتنبيهات والدائرة — في القائمة.',
    setupEyebrow: 'إعداد T2',
    setupTitle: 'إعداد دائرة الدعم',
    setupSubtitle: 'أنت، الشريك، الاحتياط ونافذة الليل — في شاشة واحدة.',
    setupSave: 'حفظ الدائرة',
  },
};
