import type { Language } from '../types';

interface WorkspaceCopy {
  eyebrow: string;
  welcome: string;
  signOut: string;
  household: string;
  roleChecklist: string;
  childCard: string;
  responder: string;
  currentState: string;
  recommendation: string;
  timeline: string;
  recentEvents: string;
  morningSummary: string;
  quickActions: string;
  doneAction: string;
  householdName: string;
  ageBand: string;
  primaryParent: string;
  caregiver: string;
  nightWindow: string;
  alerts: string;
  actions: string;
  escalations: string;
  outcome: string;
  responders: string;
  history: string;
  sessionDetail: string;
  sessionTimeline: string;
  viewDetail: string;
  noHistory: string;
  roleFocus: Record<'child' | 'parent' | 'caregiver' | 'adult', { title: string; body: string; points: [string, string, string] }>;
  stateLabels: Record<'ok' | 'watch' | 'risk' | 'critical' | 'recovery', string>;
  timelineStatus: Record<'done' | 'active' | 'waiting', string>;
  failStates: {
    waitingTitle: string;
    waitingBody: Record<'parent' | 'caregiver' | 'adult', string>;
    delayedTitle: string;
    delayedBody: Record<'parent' | 'caregiver' | 'adult', string>;
    offlineTitle: string;
    offlineBody: Record<'parent' | 'caregiver' | 'adult', string>;
    dayHint: string;
    nightHint: string;
  };
}

export const WORKSPACE_COPY: Record<Language, WorkspaceCopy> = {
  en: {
    eyebrow: 'Daily Safety Space',
    welcome: 'Welcome',
    signOut: 'Sign Out',
    household: 'Family',
    roleChecklist: 'Your Focus',
    childCard: 'Child Status',
    responder: 'Current Responder',
    currentState: 'Current Safety State',
    recommendation: 'Recommended Action',
    timeline: 'Recent Safety Timeline',
    recentEvents: 'Recent Events',
    morningSummary: 'Daily Note',
    quickActions: 'Action',
    doneAction: 'DONE',
    householdName: 'Family Name',
    ageBand: 'Child Age Band',
    primaryParent: 'Primary Parent',
    caregiver: 'Backup Support Adult',
    nightWindow: 'Night Window',
    alerts: 'Signals',
    actions: 'Actions',
    escalations: 'Backup Steps',
    outcome: 'Outcome',
    responders: 'Responders',
    history: 'Daily History',
    sessionDetail: 'Past Day Detail',
    sessionTimeline: 'Session Timeline',
    viewDetail: 'View Detail',
    noHistory: 'Completed daily safety cycles will appear here after recovery finishes.',
    roleFocus: {
      child: { title: 'Child Safe Mode', body: 'This view keeps the child calm, clear, and connected to an adult during overnight risk.', points: ['Stay close to an adult', 'Follow one clear next step', 'Keep treatment nearby'] },
      parent: { title: 'Parent Safety View', body: 'The parent view keeps the current state, next step, and response ownership clear.', points: ['See what is changing now', 'Confirm who is responding', 'Keep recovery covered'] },
      caregiver: { title: 'Support Adult View', body: 'This view stays simple and becomes active when extra family support is needed.', points: ['See when backup is needed', 'Understand what already happened', 'Take over without confusion'] },
      adult: { title: 'Adult Safety View', body: 'The adult view keeps the current state clear and supports a fast response without overload.', points: ['See the current state fast', 'Respond with one clear action', 'Stay in recovery watch until stable'] },
    },
    stateLabels: { ok: 'Stable', watch: 'Watch', risk: 'Risk', critical: 'Critical', recovery: 'Recovery' },
    timelineStatus: { done: 'Done', active: 'Active', waiting: 'Waiting' },
    failStates: {
      waitingTitle: 'Waiting for data',
      waitingBody: {
        parent: 'The system is waiting for a fresh sensor signal before asking the family to act.',
        caregiver: 'Stay available, but wait for a fresh signal before stepping in.',
        adult: 'Keep treatment nearby and wait for the next fresh sensor update.',
      },
      delayedTitle: 'Data is delayed',
      delayedBody: {
        parent: 'Signal confidence is lower right now. Keep watch, but avoid overreacting to stale data.',
        caregiver: 'Data is delayed. Stay reachable while the system waits for a fresher signal.',
        adult: 'Confidence is reduced right now. Stay aware and wait for a fresher update.',
      },
      offlineTitle: 'Device looks offline',
      offlineBody: {
        parent: 'Check the sensor connection first. The system should not push strong guidance without live data.',
        caregiver: 'The device may be offline. Stay ready, but wait for the family or fresh data to confirm the next step.',
        adult: 'Check the sensor and connection first before relying on the current reading.',
      },
      dayHint: 'Day mode keeps support lighter and less intrusive.',
      nightHint: 'Night mode keeps support tighter and more protective.',
    },
  },
  ru: {
    eyebrow: 'Пространство Ежедневной Поддержки',
    welcome: 'Добро пожаловать',
    signOut: 'Выйти',
    household: 'Семья',
    roleChecklist: 'Ваш Фокус',
    childCard: 'Статус Ребёнка',
    responder: 'Кто Отвечает Сейчас',
    currentState: 'Текущее Состояние',
    recommendation: 'Рекомендуемое Действие',
    timeline: 'Последние События',
    recentEvents: 'Последние События',
    morningSummary: 'Итог За День',
    quickActions: 'Действие',
    doneAction: 'ГОТОВО',
    householdName: 'Название Семьи',
    ageBand: 'Возраст Ребёнка',
    primaryParent: 'Основной Родитель',
    caregiver: 'Резервный Помогающий Взрослый',
    nightWindow: 'Ночное Окно',
    alerts: 'Сигналы',
    actions: 'Действия',
    escalations: 'Подключения Резерва',
    outcome: 'Итог',
    responders: 'Участники Реакции',
    history: 'История Дней',
    sessionDetail: 'Детали Прошлого Дня',
    sessionTimeline: 'Лента Сессии',
    viewDetail: 'Открыть Детали',
    noHistory: 'Завершённые циклы поддержки появятся здесь после окончания восстановления.',
    roleFocus: {
      child: { title: 'Детский Спокойный Режим', body: 'Этот экран удерживает ребёнка в спокойном и понятном состоянии рядом со взрослым во время риска.', points: ['Оставаться рядом со взрослым', 'Видеть только следующий шаг', 'Держать лечение под рукой'] },
      parent: { title: 'Экран Родителя', body: 'Экран родителя помогает быстро понять текущее состояние, следующее действие и кто уже отвечает.', points: ['Понимать, что меняется сейчас', 'Видеть, кто уже отвечает', 'Довести цикл до стабильного восстановления'] },
      caregiver: { title: 'Экран Поддержки', body: 'Экран помогающего взрослого остаётся простым и включается, когда действительно нужна подстраховка.', points: ['Понять, когда нужна подстраховка', 'Увидеть, что уже произошло', 'Принять ситуацию без путаницы'] },
      adult: { title: 'Экран Взрослого С T1D', body: 'Этот экран помогает быстро увидеть состояние и отреагировать без перегруза.', points: ['Сразу видеть текущее состояние', 'Отвечать одним понятным действием', 'Оставаться под наблюдением до стабилизации'] },
    },
    stateLabels: { ok: 'Стабильно', watch: 'Наблюдение', risk: 'Риск', critical: 'Критично', recovery: 'Восстановление' },
    timelineStatus: { done: 'Готово', active: 'Активно', waiting: 'Ожидает' },
    failStates: {
      waitingTitle: 'Ожидание данных',
      waitingBody: {
        parent: 'Система ждёт свежий сигнал сенсора, прежде чем просить семью действовать.',
        caregiver: 'Оставайтесь на связи, но дождитесь свежего сигнала, прежде чем подключаться.',
        adult: 'Держите лечение рядом и дождитесь следующего свежего обновления сенсора.',
      },
      delayedTitle: 'Данные приходят с задержкой',
      delayedBody: {
        parent: 'Надёжность сигнала сейчас ниже. Наблюдайте спокойно и не реагируйте слишком резко на устаревшие данные.',
        caregiver: 'Данные запаздывают. Оставайтесь на связи, пока система ждёт более свежий сигнал.',
        adult: 'Надёжность сейчас снижена. Сохраняйте внимание и дождитесь более свежего обновления.',
      },
      offlineTitle: 'Похоже, устройство не в сети',
      offlineBody: {
        parent: 'Сначала проверьте сенсор и соединение. Без живых данных система не должна давать жёсткие указания.',
        caregiver: 'Устройство может быть не в сети. Оставайтесь готовы, но дождитесь подтверждения от семьи или свежих данных.',
        adult: 'Сначала проверьте сенсор и соединение, прежде чем полагаться на текущее значение.',
      },
      dayHint: 'Дневной режим мягче и меньше вмешивается.',
      nightHint: 'Ночной режим строже и внимательнее защищает.',
    },
  },
  uk: {
    eyebrow: 'Простір Щоденної Підтримки',
    welcome: 'Ласкаво просимо',
    signOut: 'Вийти',
    household: 'Сімʼя',
    roleChecklist: 'Ваш Фокус',
    childCard: 'Статус Дитини',
    responder: 'Хто Відповідає Зараз',
    currentState: 'Поточний Стан Безпеки',
    recommendation: 'Рекомендована Дія',
    timeline: 'Стрічка Подій',
    recentEvents: 'Останні Події',
    morningSummary: 'Підсумок За День',
    quickActions: 'Дія',
    doneAction: 'ГОТОВО',
    householdName: 'Назва Сімʼї',
    ageBand: 'Вік Дитини',
    primaryParent: 'Основний З Батьків',
    caregiver: 'Резервний Дорослий Для Підтримки',
    nightWindow: 'Нічне Вікно',
    alerts: 'Сигнали',
    actions: 'Дії',
    escalations: 'Підключення Резерву',
    outcome: 'Підсумок',
    responders: 'Учасники Реакції',
    history: 'Історія Днів',
    sessionDetail: 'Деталі Минулого Дня',
    sessionTimeline: 'Стрічка Сесії',
    viewDetail: 'Відкрити Деталі',
    noHistory: 'Завершені цикли підтримки з’являться тут після завершення спостереження за відновленням.',
    roleFocus: {
      child: { title: 'Дитячий Спокійний Режим', body: 'Цей екран тримає дитину в спокійному й зрозумілому стані поруч із дорослим під час ризику.', points: ['Бути поруч із дорослим', 'Бачити лише наступний крок', 'Тримати лікування поруч'] },
      parent: { title: 'Батьківський Контроль', body: 'Екран для батьків зосереджений на відповідальності, підтвердженні реакції та передачі підтримки до того, як ситуація стане небезпечною.', points: ['Розуміти, що змінюється зараз', 'Бачити, хто вже відповідає', 'Довести цикл до стабільного відновлення'] },
      caregiver: { title: 'Резервний Екран Підтримки', body: 'Екран дорослого для підтримки активується, коли потрібна підстраховка, і чітко показує, хто бере ситуацію на себе.', points: ['Побачити, коли потрібна підстраховка', 'Зрозуміти, що вже сталося', 'Взяти ситуацію без плутанини'] },
      adult: { title: 'Режим Самостійного Нагляду', body: 'Режим для дорослого використовує ту саму логіку безпеки, але без сімейного фокусу на передачі підтримки.', points: ['Швидко бачити поточний стан', 'Відповісти однією чіткою дією', 'Залишатися під наглядом до стабілізації'] },
    },
    stateLabels: { ok: 'Стабільно', watch: 'Нагляд', risk: 'Ризик', critical: 'Критично', recovery: 'Відновлення' },
    timelineStatus: { done: 'Готово', active: 'Активно', waiting: 'Очікує' },
    failStates: {
      waitingTitle: 'Очікування даних',
      waitingBody: {
        parent: 'Система чекає на свіжий сигнал сенсора, перш ніж просити родину діяти.',
        caregiver: 'Будьте на звʼязку, але дочекайтеся свіжого сигналу перед тим, як втручатися.',
        adult: 'Тримайте лікування поруч і дочекайтеся наступного свіжого оновлення сенсора.',
      },
      delayedTitle: 'Дані надходять із затримкою',
      delayedBody: {
        parent: 'Надійність сигналу зараз нижча. Спокійно спостерігайте й не реагуйте надто різко на застарілі дані.',
        caregiver: 'Дані запізнюються. Будьте на звʼязку, поки система чекає свіжіший сигнал.',
        adult: 'Надійність зараз нижча. Зберігайте уважність і дочекайтеся свіжішого оновлення.',
      },
      offlineTitle: 'Схоже, пристрій не в мережі',
      offlineBody: {
        parent: 'Спершу перевірте сенсор і зʼєднання. Без живих даних система не має давати жорсткі вказівки.',
        caregiver: 'Пристрій може бути не в мережі. Будьте готові, але дочекайтеся підтвердження від родини або свіжих даних.',
        adult: 'Спершу перевірте сенсор і зʼєднання, перш ніж покладатися на поточне значення.',
      },
      dayHint: 'Денний режим мʼякший і менше втручається.',
      nightHint: 'Нічний режим уважніший і захищає активніше.',
    },
  },
  es: {
    eyebrow: 'Espacio De Seguridad Diaria',
    welcome: 'Bienvenido',
    signOut: 'Cerrar sesión',
    household: 'Familia',
    roleChecklist: 'Tu Enfoque',
    childCard: 'Estado Del Niño',
    responder: 'Responsable Actual',
    currentState: 'Estado Actual De Seguridad',
    recommendation: 'Acción Recomendada',
    timeline: 'Línea De Seguridad',
    recentEvents: 'Eventos Recientes',
    morningSummary: 'Resumen De La Mañana',
    quickActions: 'Acciones Rápidas',
    doneAction: 'HECHO',
    householdName: 'Nombre Del Hogar',
    ageBand: 'Edad Del Niño',
    primaryParent: 'Progenitor Principal',
    caregiver: 'Adulto De Apoyo De Respaldo',
    nightWindow: 'Ventana Nocturna',
    alerts: 'Alertas',
    actions: 'Acciones',
    escalations: 'Escalaciones',
    outcome: 'Resultado',
    responders: 'Personas Que Respondieron',
    history: 'Historial Diario',
    sessionDetail: 'Detalle Del Día Anterior',
    sessionTimeline: 'Línea De La Sesión',
    viewDetail: 'Ver Detalle',
    noHistory: 'Los ciclos completados aparecerán aquí después de que termine la observación de recuperación.',
    roleFocus: {
      child: { title: 'Modo Seguro Infantil', body: 'Esta vista mantiene al niño tranquilo, orientado y junto a un adulto durante el riesgo nocturno.', points: ['Permanecer con un adulto', 'Ver solo el siguiente paso', 'Mantener el tratamiento cerca'] },
      parent: { title: 'Vista De Control Para Padres', body: 'La vista del padre se centra en la responsabilidad, la confirmación y el traspaso antes de que la noche se vuelva insegura.', points: ['Ver qué cambia ahora', 'Saber quién está respondiendo', 'Mantener la recuperación cubierta'] },
      caregiver: { title: 'Vista De Respaldo Del Adulto De Apoyo', body: 'Esta vista se activa cuando hace falta apoyo extra y deja claro quién toma el control.', points: ['Ver cuándo hace falta apoyo', 'Entender qué ya ocurrió', 'Asumir sin confusión'] },
      adult: { title: 'Vista De Vigilancia Independiente', body: 'El modo adulto heredado sigue la misma lógica de seguridad nocturna, pero sin el foco familiar.', points: ['Ver el estado actual rápido', 'Responder con una sola acción', 'Seguir en recuperación hasta estabilizarse'] },
    },
    stateLabels: { ok: 'Estable', watch: 'Vigilancia', risk: 'Riesgo', critical: 'Crítico', recovery: 'Recuperación' },
    timelineStatus: { done: 'Hecho', active: 'Activo', waiting: 'En Espera' },
    failStates: {
      waitingTitle: 'Esperando datos',
      waitingBody: {
        parent: 'El sistema espera una señal fresca del sensor antes de pedir a la familia que actúe.',
        caregiver: 'Mantente disponible, pero espera una señal fresca antes de intervenir.',
        adult: 'Mantén el tratamiento cerca y espera la siguiente actualización fresca del sensor.',
      },
      delayedTitle: 'Los datos llegan con retraso',
      delayedBody: {
        parent: 'La confianza en la señal es menor ahora. Observa con calma y evita reaccionar demasiado a datos desactualizados.',
        caregiver: 'Los datos están retrasados. Mantente localizable mientras el sistema espera una señal más fresca.',
        adult: 'La confianza está reducida ahora. Mantente atento y espera una actualización más fresca.',
      },
      offlineTitle: 'Parece que el dispositivo está sin conexión',
      offlineBody: {
        parent: 'Primero revisa el sensor y la conexión. Sin datos en vivo el sistema no debe dar indicaciones fuertes.',
        caregiver: 'El dispositivo puede estar sin conexión. Mantente listo, pero espera confirmación de la familia o datos frescos.',
        adult: 'Primero revisa el sensor y la conexión antes de confiar en la lectura actual.',
      },
      dayHint: 'El modo diurno mantiene el apoyo más suave y menos intrusivo.',
      nightHint: 'El modo nocturno mantiene el apoyo más atento y protector.',
    },
  },
  fr: {
    eyebrow: 'Espace De Sécurité Quotidienne',
    welcome: 'Bienvenue',
    signOut: 'Se déconnecter',
    household: 'Famille',
    roleChecklist: 'Votre Focus',
    childCard: 'État De L’Enfant',
    responder: 'Répondant Actuel',
    currentState: 'État Actuel De Sécurité',
    recommendation: 'Action Recommandée',
    timeline: 'Timeline De Sécurité',
    recentEvents: 'Événements Récents',
    morningSummary: 'Résumé Du Matin',
    quickActions: 'Actions Rapides',
    doneAction: 'FAIT',
    householdName: 'Nom Du Foyer',
    ageBand: 'Âge De L’Enfant',
    primaryParent: 'Parent Principal',
    caregiver: 'Adulte De Soutien De Secours',
    nightWindow: 'Fenêtre De Nuit',
    alerts: 'Alertes',
    actions: 'Actions',
    escalations: 'Escalades',
    outcome: 'Résultat',
    responders: 'Répondants',
    history: 'Historique Quotidien',
    sessionDetail: 'Détail Du Jour Passé',
    sessionTimeline: 'Timeline De La Session',
    viewDetail: 'Voir Le Détail',
    noHistory: 'Les cycles terminés apparaîtront ici une fois la surveillance de récupération achevée.',
    roleFocus: {
      child: { title: 'Mode Sûr Enfant', body: 'Cette vue garde l’enfant calme, orienté et proche d’un adulte pendant un risque nocturne.', points: ['Rester avec un adulte', 'Voir seulement l’étape suivante', 'Garder le traitement à portée'] },
      parent: { title: 'Vue De Contrôle Parent', body: 'La vue parent met l’accent sur la responsabilité, la confirmation et le relais avant qu’une nuit ne devienne dangereuse.', points: ['Voir ce qui change maintenant', 'Savoir qui répond déjà', 'Maintenir la récupération couverte'] },
      caregiver: { title: 'Vue De Secours De L’Adulte De Soutien', body: 'Cette vue s’active quand un soutien supplémentaire devient nécessaire et rend la reprise explicite.', points: ['Voir quand le soutien est nécessaire', 'Comprendre ce qui s’est passé', 'Prendre le relais sans confusion'] },
      adult: { title: 'Vue De Veille Indépendante', body: 'Le mode adulte historique suit la même logique de sécurité nocturne, sans le focus familial.', points: ['Voir l’état actuel rapidement', 'Répondre avec une seule action', 'Rester en récupération jusqu’à stabilisation'] },
    },
    stateLabels: { ok: 'Stable', watch: 'Surveillance', risk: 'Risque', critical: 'Critique', recovery: 'Récupération' },
    timelineStatus: { done: 'Terminé', active: 'Actif', waiting: 'En Attente' },
    failStates: {
      waitingTitle: 'En attente de données',
      waitingBody: {
        parent: 'Le système attend un signal capteur plus frais avant de demander à la famille d’agir.',
        caregiver: 'Restez disponible, mais attendez un signal frais avant d’intervenir.',
        adult: 'Gardez le traitement à portée et attendez la prochaine mise à jour fraîche du capteur.',
      },
      delayedTitle: 'Les données sont retardées',
      delayedBody: {
        parent: 'La confiance dans le signal est plus faible pour le moment. Surveillez calmement sans sur-réagir à des données anciennes.',
        caregiver: 'Les données sont retardées. Restez joignable pendant que le système attend un signal plus frais.',
        adult: 'La confiance est réduite pour le moment. Restez attentif et attendez une mise à jour plus fraîche.',
      },
      offlineTitle: 'L’appareil semble hors ligne',
      offlineBody: {
        parent: 'Vérifiez d’abord le capteur et la connexion. Sans données en direct, le système ne doit pas donner d’instructions trop fortes.',
        caregiver: 'L’appareil peut être hors ligne. Restez prêt, mais attendez une confirmation de la famille ou des données fraîches.',
        adult: 'Vérifiez d’abord le capteur et la connexion avant de vous fier à la valeur actuelle.',
      },
      dayHint: 'Le mode jour reste plus léger et moins intrusif.',
      nightHint: 'Le mode nuit reste plus serré et plus protecteur.',
    },
  },
  de: {
    eyebrow: 'Raum Für Tägliche Sicherheit',
    welcome: 'Willkommen',
    signOut: 'Abmelden',
    household: 'Familie',
    roleChecklist: 'Ihr Fokus',
    childCard: 'Kindstatus',
    responder: 'Aktuell Verantwortlich',
    currentState: 'Aktueller Sicherheitsstatus',
    recommendation: 'Empfohlene Aktion',
    timeline: 'Sicherheitsverlauf',
    recentEvents: 'Letzte Ereignisse',
    morningSummary: 'Morgenzusammenfassung',
    quickActions: 'Schnelle Aktionen',
    doneAction: 'FERTIG',
    householdName: 'Haushaltsname',
    ageBand: 'Altersgruppe Des Kindes',
    primaryParent: 'Hauptelternteil',
    caregiver: 'Unterstützende Person Im Backup',
    nightWindow: 'Nachtfenster',
    alerts: 'Warnungen',
    actions: 'Aktionen',
    escalations: 'Eskalationen',
    outcome: 'Ergebnis',
    responders: 'Reagierende Personen',
    history: 'Tagesverlauf',
    sessionDetail: 'Details Des Vergangenen Tages',
    sessionTimeline: 'Sitzungs-Timeline',
    viewDetail: 'Details Anzeigen',
    noHistory: 'Abgeschlossene Sicherheitszyklen erscheinen hier, sobald die Erholungsbeobachtung beendet ist.',
    roleFocus: {
      child: { title: 'Kind-Sicherheitsmodus', body: 'Diese Ansicht hält das Kind nachts ruhig, klar orientiert und in der Nähe eines Erwachsenen.', points: ['In der Nähe eines Erwachsenen bleiben', 'Nur den nächsten Schritt sehen', 'Behandlung griffbereit halten'] },
      parent: { title: 'Eltern-Kontrollansicht', body: 'Die Elternansicht fokussiert Verantwortung, Bestätigung und Übergabe, bevor eine Nacht unsicher wird.', points: ['Sehen, was sich gerade ändert', 'Erkennen, wer reagiert', 'Erholung verlässlich begleiten'] },
      caregiver: { title: 'Backup-Ansicht Für Unterstützung', body: 'Diese Ansicht wird aktiv, wenn zusätzliche Unterstützung nötig ist, und macht die Übernahme explizit.', points: ['Sehen, wann Backup nötig ist', 'Verstehen, was schon passiert ist', 'Klar und ohne Verwirrung übernehmen'] },
      adult: { title: 'Unabhängige Sicherheitsansicht', body: 'Der Erwachsenenmodus folgt derselben Sicherheitslogik, aber ohne Familienübergabe als Schwerpunkt.', points: ['Aktuellen Zustand schnell sehen', 'Mit einer klaren Aktion reagieren', 'Bis zur Stabilisierung in Beobachtung bleiben'] },
    },
    stateLabels: { ok: 'Stabil', watch: 'Beobachten', risk: 'Risiko', critical: 'Kritisch', recovery: 'Erholung' },
    timelineStatus: { done: 'Fertig', active: 'Aktiv', waiting: 'Wartend' },
    failStates: {
      waitingTitle: 'Warten auf Daten',
      waitingBody: {
        parent: 'Das System wartet auf ein frisches Sensorsignal, bevor es die Familie zum Handeln auffordert.',
        caregiver: 'Bleiben Sie erreichbar, aber warten Sie auf ein frisches Signal, bevor Sie eingreifen.',
        adult: 'Halten Sie die Behandlung bereit und warten Sie auf das nächste frische Sensor-Update.',
      },
      delayedTitle: 'Daten sind verzögert',
      delayedBody: {
        parent: 'Die Signalsicherheit ist im Moment geringer. Beobachten Sie ruhig und reagieren Sie nicht zu stark auf alte Daten.',
        caregiver: 'Die Daten sind verzögert. Bleiben Sie erreichbar, während das System auf ein frischeres Signal wartet.',
        adult: 'Die Sicherheit ist im Moment geringer. Bleiben Sie aufmerksam und warten Sie auf ein frischeres Update.',
      },
      offlineTitle: 'Gerät scheint offline zu sein',
      offlineBody: {
        parent: 'Prüfen Sie zuerst Sensor und Verbindung. Ohne Live-Daten sollte das System keine starken Hinweise geben.',
        caregiver: 'Das Gerät könnte offline sein. Bleiben Sie bereit, warten Sie aber auf Bestätigung durch die Familie oder frische Daten.',
        adult: 'Prüfen Sie zuerst Sensor und Verbindung, bevor Sie sich auf den aktuellen Wert verlassen.',
      },
      dayHint: 'Der Tagmodus bleibt leichter und weniger aufdringlich.',
      nightHint: 'Der Nachtmodus bleibt enger und schützender.',
    },
  },
  zh: {
    eyebrow: '日常安全工作区',
    welcome: '欢迎',
    signOut: '退出登录',
    household: '家庭',
    roleChecklist: '你的重点',
    childCard: '孩子状态',
    responder: '当前响应人',
    currentState: '当前安全状态',
    recommendation: '建议动作',
    timeline: '安全时间线',
    recentEvents: '最近事件',
    morningSummary: '每日摘要',
    quickActions: '快捷操作',
    doneAction: '完成',
    householdName: '家庭名称',
    ageBand: '孩子年龄段',
    primaryParent: '主要家长',
    caregiver: '后备支持的大人',
    nightWindow: '夜间时间窗',
    alerts: '提醒数',
    actions: '动作数',
    escalations: '升级数',
    outcome: '结果',
    responders: '响应人员',
    history: '每日历史',
    sessionDetail: '过往详情',
    sessionTimeline: '会话时间线',
    viewDetail: '查看详情',
    noHistory: '恢复观察结束后，已完成的日常记录会显示在这里。',
    roleFocus: {
      child: { title: '儿童安全模式', body: '这个视图让孩子在夜间风险中保持平静、明确，并始终靠近成人。', points: ['待在成人身边', '只看下一步', '把处理用品放在手边'] },
      parent: { title: '家长控制视图', body: '家长视图聚焦责任、确认和交接，避免夜间事件升级为危险。', points: ['看到现在的变化', '知道谁正在响应', '持续覆盖恢复过程'] },
      caregiver: { title: '后备支持视图', body: '当需要额外支持时，这个视图会被激活，并明确显示谁来接手。', points: ['看到何时需要后备支持', '了解已经发生了什么', '清楚接手，不混乱'] },
      adult: { title: '独立夜间监护视图', body: '遗留成人模式仍使用同样的夜间安全逻辑，但不强调家庭交接。', points: ['快速看到当前状态', '用一个明确动作回应', '保持恢复观察直到稳定'] },
    },
    stateLabels: { ok: '稳定', watch: '观察中', risk: '风险', critical: '危急', recovery: '恢复中' },
    timelineStatus: { done: '完成', active: '进行中', waiting: '等待中' },
    failStates: {
      waitingTitle: '等待数据',
      waitingBody: {
        parent: '系统正在等待新的传感器信号，然后才会要求家庭采取行动。',
        caregiver: '请保持可联系状态，但在介入前先等待新的信号。',
        adult: '请把处理用品放在手边，并等待下一次新的传感器更新。',
      },
      delayedTitle: '数据有延迟',
      delayedBody: {
        parent: '当前信号可信度较低。请保持观察，不要对过旧数据反应过度。',
        caregiver: '数据有延迟。系统等待更新信号时，请保持可联系状态。',
        adult: '当前可信度较低。请保持警觉，并等待更新的信号。',
      },
      offlineTitle: '设备似乎离线',
      offlineBody: {
        parent: '请先检查传感器和连接。没有实时数据时，系统不应给出过强指引。',
        caregiver: '设备可能离线。请保持准备，但先等待家庭确认或新的数据。',
        adult: '请先检查传感器和连接，再参考当前读数。',
      },
      dayHint: '白天模式更轻、更少打扰。',
      nightHint: '夜间模式更紧密，也更有保护性。',
    },
  },
  ja: {
    eyebrow: 'デイリーセーフティ・ワークスペース',
    welcome: 'ようこそ',
    signOut: 'サインアウト',
    household: '家族',
    roleChecklist: 'いまの重点',
    childCard: '子どもの状態',
    responder: '現在の対応者',
    currentState: '現在の安全状態',
    recommendation: '推奨アクション',
    timeline: 'セーフティタイムライン',
    recentEvents: '最近のイベント',
    morningSummary: 'デイリーサマリー',
    quickActions: 'クイックアクション',
    doneAction: '完了',
    householdName: '家族名',
    ageBand: '子どもの年齢帯',
    primaryParent: '主担当の保護者',
    caregiver: 'バックアップの支える大人',
    nightWindow: '夜間ウィンドウ',
    alerts: 'アラート数',
    actions: '対応数',
    escalations: 'エスカレーション数',
    outcome: '結果',
    responders: '対応者',
    history: '日次履歴',
    sessionDetail: '過去の詳細',
    sessionTimeline: 'セッションのタイムライン',
    viewDetail: '詳細を見る',
    noHistory: '回復見守りが完了すると、完了した記録がここに表示されます。',
    roleFocus: {
      child: { title: '子どもセーフモード', body: 'この画面は夜間リスクの間、子どもを落ち着かせ、大人のそばに保ちます。', points: ['大人のそばにいる', '次の一歩だけを見る', '対処手段を手元に置く'] },
      parent: { title: '保護者コントロールビュー', body: '保護者ビューは責任、確認、引き継ぎに集中し、夜間の危険化を防ぎます。', points: ['今の変化を把握する', '誰が対応中か確認する', '回復見守りを切らさない'] },
      caregiver: { title: 'バックアップ支援ビュー', body: '追加の支援が必要になるとこのビューが起動し、引き継ぎを明確にします。', points: ['支援が必要な瞬間を見る', '何が起きたか理解する', '迷わず引き継ぐ'] },
      adult: { title: '自立監視ビュー', body: '従来の成人モードも同じ夜間安全ロジックに従いますが、家族の引き継ぎは中心ではありません。', points: ['現在の状態をすぐ見る', 'ひとつの明確な操作で応答する', '安定まで回復見守りを続ける'] },
    },
    stateLabels: { ok: '安定', watch: '見守り', risk: 'リスク', critical: '重大', recovery: '回復中' },
    timelineStatus: { done: '完了', active: '進行中', waiting: '待機中' },
    failStates: {
      waitingTitle: 'データ待機中',
      waitingBody: {
        parent: 'システムは家族に行動を求める前に、新しいセンサー信号を待っています。',
        caregiver: '連絡が取れる状態を保ちつつ、介入前に新しい信号を待ってください。',
        adult: '対処手段を手元に置き、次の新しいセンサー更新を待ってください。',
      },
      delayedTitle: 'データに遅れがあります',
      delayedBody: {
        parent: 'いまは信号の信頼度が低めです。古いデータに過剰反応せず、落ち着いて見守ってください。',
        caregiver: 'データに遅れがあります。システムが新しい信号を待つ間、連絡可能な状態を保ってください。',
        adult: 'いまは信頼度が下がっています。注意を保ちつつ、新しい更新を待ってください。',
      },
      offlineTitle: 'デバイスがオフラインの可能性があります',
      offlineBody: {
        parent: 'まずセンサーと接続を確認してください。ライブデータなしでは強い案内を出すべきではありません。',
        caregiver: 'デバイスがオフラインかもしれません。準備は保ちつつ、家族の確認か新しいデータを待ってください。',
        adult: '現在の値を頼る前に、まずセンサーと接続を確認してください。',
      },
      dayHint: '昼モードはより軽く、干渉も少なめです。',
      nightHint: '夜モードはより密に見守り、保護を強めます。',
    },
  },
  pt: {
    eyebrow: 'Espaço De Segurança Diária',
    welcome: 'Bem-vindo',
    signOut: 'Sair',
    household: 'Família',
    roleChecklist: 'Seu Foco',
    childCard: 'Estado Da Criança',
    responder: 'Responsável Atual',
    currentState: 'Estado Atual De Segurança',
    recommendation: 'Ação Recomendada',
    timeline: 'Linha De Segurança',
    recentEvents: 'Eventos Recentes',
    morningSummary: 'Resumo Diário',
    quickActions: 'Ações Rápidas',
    doneAction: 'FEITO',
    householdName: 'Nome Da Família',
    ageBand: 'Faixa Etária Da Criança',
    primaryParent: 'Responsável Principal',
    caregiver: 'Adulto De Apoio De Reserva',
    nightWindow: 'Janela Noturna',
    alerts: 'Alertas',
    actions: 'Ações',
    escalations: 'Escalações',
    outcome: 'Resultado',
    responders: 'Quem Respondeu',
    history: 'Histórico Diário',
    sessionDetail: 'Detalhe Anterior',
    sessionTimeline: 'Linha Da Sessão',
    viewDetail: 'Ver Detalhe',
    noHistory: 'Os ciclos concluídos aparecerão aqui depois que a observação de recuperação terminar.',
    roleFocus: {
      child: { title: 'Modo Seguro Infantil', body: 'Esta visão mantém a criança calma, orientada e perto de um adulto durante o risco noturno.', points: ['Ficar perto de um adulto', 'Ver apenas o próximo passo', 'Manter o tratamento por perto'] },
      parent: { title: 'Visão De Controle Dos Pais', body: 'A visão dos pais foca responsabilidade, confirmação e passagem de apoio antes que a situação fique insegura.', points: ['Ver o que está mudando agora', 'Saber quem está respondendo', 'Manter a recuperação coberta'] },
      caregiver: { title: 'Visão De Apoio Reserva', body: 'Esta visão é ativada quando apoio extra é necessário e deixa claro quem assume a responsabilidade.', points: ['Ver quando o apoio é necessário', 'Entender o que já aconteceu', 'Assumir sem confusão'] },
      adult: { title: 'Visão De Vigilância Independente', body: 'O modo adulto segue a mesma lógica de segurança, mas sem foco principal na passagem familiar.', points: ['Ver o estado atual rapidamente', 'Responder com uma ação clara', 'Seguir em recuperação até estabilizar'] },
    },
    stateLabels: { ok: 'Estável', watch: 'Observação', risk: 'Risco', critical: 'Crítico', recovery: 'Recuperação' },
    timelineStatus: { done: 'Concluído', active: 'Ativo', waiting: 'Aguardando' },
    failStates: {
      waitingTitle: 'Aguardando dados',
      waitingBody: {
        parent: 'O sistema está aguardando um sinal novo do sensor antes de pedir ação à família.',
        caregiver: 'Fique disponível, mas espere um sinal novo antes de intervir.',
        adult: 'Mantenha o tratamento por perto e aguarde a próxima atualização nova do sensor.',
      },
      delayedTitle: 'Os dados estão atrasados',
      delayedBody: {
        parent: 'A confiança no sinal está menor agora. Observe com calma e evite reagir demais a dados antigos.',
        caregiver: 'Os dados estão atrasados. Fique acessível enquanto o sistema espera um sinal mais novo.',
        adult: 'A confiança está reduzida agora. Mantenha atenção e aguarde uma atualização mais nova.',
      },
      offlineTitle: 'O dispositivo parece offline',
      offlineBody: {
        parent: 'Verifique primeiro o sensor e a conexão. Sem dados ao vivo o sistema não deve dar instruções fortes.',
        caregiver: 'O dispositivo pode estar offline. Fique pronto, mas espere confirmação da família ou dados novos.',
        adult: 'Verifique primeiro o sensor e a conexão antes de confiar no valor atual.',
      },
      dayHint: 'O modo diurno mantém o suporte mais leve e menos intrusivo.',
      nightHint: 'O modo noturno mantém o suporte mais atento e protetor.',
    },
  },
  he: {
    eyebrow: 'מרחב לבטיחות יומית',
    welcome: 'ברוכים הבאים',
    signOut: 'התנתקות',
    household: 'משפחה',
    roleChecklist: 'הפוקוס שלך',
    childCard: 'מצב הילד',
    responder: 'מי שמגיב עכשיו',
    currentState: 'מצב הבטיחות הנוכחי',
    recommendation: 'פעולה מומלצת',
    timeline: 'ציר בטיחות',
    recentEvents: 'אירועים אחרונים',
    morningSummary: 'סיכום יומי',
    quickActions: 'פעולות מהירות',
    doneAction: 'בוצע',
    householdName: 'שם המשפחה',
    ageBand: 'טווח גיל הילד',
    primaryParent: 'הורה ראשי',
    caregiver: 'מבוגר תומך לגיבוי',
    nightWindow: 'חלון לילה',
    alerts: 'התראות',
    actions: 'פעולות',
    escalations: 'הסלמות',
    outcome: 'תוצאה',
    responders: 'מגיבים',
    history: 'היסטוריה יומית',
    sessionDetail: 'פרטי יום קודם',
    sessionTimeline: 'ציר זמן של הסשן',
    viewDetail: 'פתח פרטים',
    noHistory: 'מחזורים שהושלמו יופיעו כאן אחרי שמעקב ההתאוששות יסתיים.',
    roleFocus: {
      child: { title: 'מצב בטוח לילד', body: 'התצוגה הזו משאירה את הילד רגוע, ברור ובקרבת מבוגר בזמן סיכון לילי.', points: ['להישאר ליד מבוגר', 'לראות רק את הצעד הבא', 'להחזיק טיפול בהישג יד'] },
      parent: { title: 'תצוגת שליטה להורה', body: 'תצוגת ההורה ממקדת אחריות, אישור והעברה לפני שמצב הלילה נהיה מסוכן.', points: ['לראות מה משתנה עכשיו', 'לדעת מי כבר מגיב', 'לשמור על כיסוי עד התאוששות יציבה'] },
      caregiver: { title: 'תצוגת גיבוי לתמיכה', body: 'התצוגה הזו מופעלת כשצריך תמיכה נוספת ומבהירה מי לוקח אחריות.', points: ['לראות מתי צריך גיבוי', 'להבין מה כבר קרה', 'לקחת אחריות בלי בלבול'] },
      adult: { title: 'תצוגת מעקב עצמאית', body: 'מצב המבוגר הוותיק עדיין פועל לפי אותה לוגיקת לילה, אך בלי דגש על העברה משפחתית.', points: ['לראות מהר את המצב הנוכחי', 'להגיב בפעולה אחת ברורה', 'להישאר במעקב עד ליציבות'] },
    },
    stateLabels: { ok: 'יציב', watch: 'מעקב', risk: 'סיכון', critical: 'קריטי', recovery: 'התאוששות' },
    timelineStatus: { done: 'הושלם', active: 'פעיל', waiting: 'ממתין' },
    failStates: {
      waitingTitle: 'ממתין לנתונים',
      waitingBody: {
        parent: 'המערכת ממתינה לאות חיישן חדש לפני שהיא מבקשת מהמשפחה לפעול.',
        caregiver: 'הישארו זמינים, אבל המתינו לאות חדש לפני שמתערבים.',
        adult: 'שמרו את הטיפול קרוב והמתינו לעדכון חיישן חדש.',
      },
      delayedTitle: 'הנתונים מתעכבים',
      delayedBody: {
        parent: 'רמת הביטחון באות נמוכה יותר כרגע. המשיכו לעקוב ברוגע ואל תגיבו בעוצמה לנתונים ישנים.',
        caregiver: 'הנתונים מתעכבים. הישארו זמינים בזמן שהמערכת ממתינה לאות חדש יותר.',
        adult: 'רמת הביטחון נמוכה יותר כרגע. הישארו ערניים והמתינו לעדכון חדש יותר.',
      },
      offlineTitle: 'נראה שהמכשיר לא מחובר',
      offlineBody: {
        parent: 'בדקו קודם את החיישן והחיבור. בלי נתונים חיים המערכת לא אמורה לתת הנחיות חזקות.',
        caregiver: 'המכשיר עשוי להיות לא מחובר. הישארו מוכנים, אבל המתינו לאישור מהמשפחה או לנתונים חדשים.',
        adult: 'בדקו קודם את החיישן והחיבור לפני שסומכים על הערך הנוכחי.',
      },
      dayHint: 'מצב יום שומר על תמיכה קלה ופחות פולשנית.',
      nightHint: 'מצב לילה שומר על תמיכה צמודה ומגינה יותר.',
    },
  },
  ar: {
    eyebrow: 'مساحة عمل الأمان اليومي',
    welcome: 'مرحبًا',
    signOut: 'تسجيل الخروج',
    household: 'العائلة',
    roleChecklist: 'تركيزك الآن',
    childCard: 'حالة الطفل',
    responder: 'المستجيب الحالي',
    currentState: 'حالة الأمان الحالية',
    recommendation: 'الإجراء الموصى به',
    timeline: 'الخط الزمني للأمان',
    recentEvents: 'الأحداث الأخيرة',
    morningSummary: 'الملخص اليومي',
    quickActions: 'إجراءات سريعة',
    doneAction: 'تم',
    householdName: 'اسم العائلة',
    ageBand: 'الفئة العمرية للطفل',
    primaryParent: 'ولي الأمر الأساسي',
    caregiver: 'الشخص البالغ الداعم الاحتياطي',
    nightWindow: 'نافذة الليل',
    alerts: 'التنبيهات',
    actions: 'الإجراءات',
    escalations: 'التصعيدات',
    outcome: 'النتيجة',
    responders: 'المستجيبون',
    history: 'السجل اليومي',
    sessionDetail: 'تفاصيل سابقة',
    sessionTimeline: 'الخط الزمني للجلسة',
    viewDetail: 'عرض التفاصيل',
    noHistory: 'ستظهر الدورات المكتملة هنا بعد انتهاء مراقبة التعافي.',
    roleFocus: {
      child: { title: 'وضع أمان الطفل', body: 'يبقي هذا العرض الطفل هادئًا وواضح التوجيه وبالقرب من بالغ أثناء الخطر الليلي.', points: ['البقاء قرب شخص بالغ', 'رؤية الخطوة التالية فقط', 'إبقاء العلاج قريبًا'] },
      parent: { title: 'عرض تحكم ولي الأمر', body: 'يركز عرض ولي الأمر على المسؤولية والتأكيد والتسليم قبل أن تصبح الليلة غير آمنة.', points: ['رؤية ما يتغير الآن', 'معرفة من يستجيب الآن', 'متابعة التعافي حتى الاستقرار'] },
      caregiver: { title: 'عرض الدعم الاحتياطي', body: 'يعمل هذا العرض عندما تكون هناك حاجة إلى دعم إضافي ويوضح من يتولى المسؤولية.', points: ['رؤية وقت الحاجة للدعم', 'فهم ما حدث بالفعل', 'تولي الأمر من دون ارتباك'] },
      adult: { title: 'عرض المراقبة المستقلة', body: 'ما زال وضع البالغ القديم يتبع المنطق الليلي نفسه، لكن من دون التركيز على التسليم العائلي.', points: ['رؤية الحالة الحالية بسرعة', 'الاستجابة بإجراء واحد واضح', 'البقاء في المراقبة حتى الاستقرار'] },
    },
    stateLabels: { ok: 'مستقر', watch: 'مراقبة', risk: 'خطر', critical: 'حرج', recovery: 'تعافٍ' },
    timelineStatus: { done: 'مكتمل', active: 'نشط', waiting: 'بانتظار' },
    failStates: {
      waitingTitle: 'بانتظار البيانات',
      waitingBody: {
        parent: 'ينتظر النظام إشارة جديدة من المستشعر قبل أن يطلب من العائلة اتخاذ إجراء.',
        caregiver: 'ابقَ متاحًا، لكن انتظر إشارة جديدة قبل التدخل.',
        adult: 'أبقِ العلاج قريبًا وانتظر التحديث الجديد التالي من المستشعر.',
      },
      delayedTitle: 'البيانات متأخرة',
      delayedBody: {
        parent: 'موثوقية الإشارة أقل الآن. راقب بهدوء وتجنب المبالغة في التفاعل مع البيانات القديمة.',
        caregiver: 'البيانات متأخرة. ابقَ متاحًا بينما ينتظر النظام إشارة أحدث.',
        adult: 'الثقة أقل الآن. ابقَ منتبهًا وانتظر تحديثًا أحدث.',
      },
      offlineTitle: 'يبدو أن الجهاز غير متصل',
      offlineBody: {
        parent: 'تحقق أولًا من المستشعر والاتصال. من دون بيانات مباشرة لا يجب أن يعطي النظام توجيهات قوية.',
        caregiver: 'قد يكون الجهاز غير متصل. ابقَ مستعدًا، لكن انتظر تأكيد العائلة أو بيانات جديدة.',
        adult: 'تحقق أولًا من المستشعر والاتصال قبل الاعتماد على القراءة الحالية.',
      },
      dayHint: 'وضع النهار أخف وأقل إزعاجًا.',
      nightHint: 'وضع الليل أكثر قربًا وحماية.',
    },
  },
};
